### ISSUE TITLE
Using the TextField onChange event

### ISSUE THREAD

**Issue by karldd** [NoHomey/react-material-ui-keyboard#45]
I'm hoping to use the `onChange` event of the material-ui `TextField` component passed into `Keyboard`. It looks like you [overwrite this in your code](https://github.com/NoHomey/react-material-ui-keyboard/blob/master/src/Keyboard.tsx#L118), but would it be possible to keep it in there and get a callback with the current `TextField` value?

**Comment by NoHomey** [comment]
I've just released `6.2.1` by adding new callback `onInputValueChange` triggered when input changes value. The callback is called with the changed value. I hope this closes your issue. However I'm not going to let `onChange` to be used since I'm not using it internally. I developed the keyboard with the purpose to be usable as well when hardware keyboard  is available for mine [electron](https://electron.atom.io) based embedded projects and this is the reason why I'm listening on window for keyboard key press events. I did open source it so others can used too, if they need. However I've designed mainly for my personal use while still trying to satisfy others needs. I hope the new `onInputValueChange` prop is what you have requested for.
